// My-Programs/NextJS/next14_api_mysql/src/app/profile/page.tsx
'use client';

import React, { useEffect, useState } from 'react'
import $ from 'jquery/dist/jquery.slim';
import Image from 'next/image'
import qcode from '../public/images/qrcode.png';
import usrpic from '../public/users/pix.jpg';
import styles from '../page.module.css';
import {QRCodeCanvas} from 'qrcode.react';

export default function Profile({}) {
  const [firstname, setFirstname] = useState("");
  const [lastname, setLastname] = useState("");
  const [email, setEmail] = useState("");
  const [mobile, setMobile] = useState("");
  const [password, setPassword] = useState("");
  const [confpassword, setConfpassword] = useState("");
  const [message, setMessage] = useState("");
  const [userid, setUserid] = useState('');
  const [profilepic, setProfilepic] = useState('');
  const [qrcode, setQrcode] = useState('');
  const [userfile, setUserfile] = useState<File>();

  let user: any = [];

  const getFromLocalStorage = (key: string) => {
    if (!key || typeof window === 'undefined') {
        return ""
    }
    return localStorage.getItem(key)
  }

  const idno = { userid: getFromLocalStorage('USERID') ? JSON.parse(getFromLocalStorage('USERID') || '{}') : []};
  let userIdno: any = idno.userid.userid === undefined ? null : idno.userid.userid
  
  
  useEffect(() => {

    const fetchData = async (xid: any) => {
      setMessage("Pls wait, retrieving data..")
      const res = await fetch(`/api/users/${xid}`);
      res.json().then((data: any) => {
        setFirstname(data.rows[0].firstname);
        setLastname(data.rows[0].lastname);
        setEmail(data.rows[0].email);
        setMobile(data.rows[0].mobileno);
        if (data.rows[0].profilepic !== null) {
          setProfilepic(data.rows[0].profilepic);
        }
        if (data.rows[0].qrcode !== null) {
          setQrcode(data.rows[0].qrcode);
        }
      })
    }
  
    fetchData(userIdno);
    setMessage("");
  },[userIdno]);

  const updateProfile = async (e: any) => {
    e.preventDefault();

    if (password !== confpassword) {
      setMessage("New Password does not matched.");
      window.setTimeout(() => {
        setMessage("");
      }, 3000);
      return;
    }

    let response = await fetch('/api/users/profile/' + userIdno, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        "lastname": lastname,
        "firstname": firstname,
        "mobileno": mobile})            
    }).catch((e: any) => {
      setMessage(e.message);
      return;
    });
    
    const result = await response?.json()
    if (result.status === 400) {
      setMessage(result.message);
    } else {
      setMessage(result.message);
    }
    setTimeout(() => {
      setMessage('');
    }, 3000);

  }

  const changePwd = () => {
    if ($('#chgPwd').is(":checked")) {    
      $('#mfacode').prop('checked', false);
      $("#qcode-info").hide();
      $("#qcode").hide();
      $("#cpwd").show();
    } 
    else {
      $("#cpwd").hide();
    }
  }

  const enableMFA = () => {
    if ($('#mfacode').is(":checked")) {    
      if ($('#chgPwd').is(":checked")) {    
        setPassword("");
        setConfpassword("");
        $('#chgPwd').prop('checked', false);
        $("#cpwd").hide();
      }
      $("#qcode").show();
      $("#qcode-info").show();
    } else {
      $("#qcode").hide();
      $("#qcode-info").hide();
    }
  }

  const changeProfilepic = async (e: any) => {  
    e.preventDefault();
    $("#userpic").attr('src',URL.createObjectURL(e.target.files[0]));
    const file = e.target.files[0];
    setUserfile(file);

    // var xid = localStorage.getItem('USERID')?.toString();
    const formdata = new FormData();
    formdata.append('userid', userIdno || '');
    formdata.append('myImage', file);
    await fetch(`/api/users/profilepic?id=${userIdno}`, {
      body: formdata,
      method: "post",
    }).then(async (result) => {

      let data = await result.json()
      if (data.status == 200) {
        setMessage(data.message);
      } else {
        setMessage(data.message);
      }
      window.setTimeout(() => {
        setMessage("");
        window.location.reload();
      }, 3000);  
      
    }).catch((e: any) => {
      setMessage(e.message);
      return;
    });  
  }

  const activateMFA = async () => {
    var fullname = firstname + " " + lastname;

    let response = await fetch('/api/users/activatemfa/' + userIdno, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        "fullname": fullname, "isactivate": true})            
    }).catch((e: any) => {
      setMessage(e.message);
      return;
    });  
    const result = await response?.json()
    if (result.status == 200) {
      setMessage(result.message);
    } else {
      setMessage(result.message);
    }
    window.setTimeout(() => {
      setMessage("");
      window.location.reload();
    }, 3000);
  }

  const deactivateMFA = async () => {
    let response = await fetch('/api/users/activatemfa/' + userIdno, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        "isactivate": false})            
    }).catch((e: any) => {
      setMessage(e.message);
      return;
    });
    const result = await response?.json()
    if (result.status == 200) {
      setMessage(result.message);
    } else {
      setMessage(result.message);
    }
    window.setTimeout(() => {
      setMessage("");
      window.location.reload();
    }, 3000);
  }

  const changePassword = async (event: any) => {
    event.preventDefault();
    if (password !== confpassword) {
      setMessage("Password does not matched.")
      setTimeout(() => {
          setMessage("");
      }, 3000);
    }
    let response = await fetch('/api/users/changepassword/' + userIdno, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({"password": password})
    }).catch((e: any) => {
      setMessage(e.message);
      return;
    });
    
    const result = await response?.json()
    if (result.status === 400) {
      setMessage(result.message);
    } else {
      setMessage(result.message);
    }
    setTimeout(() => {
      setMessage('');
    }, 3000);

  }


  return (
    <div className="container">
          <main className={styles.cardprofiletop}>

      <div className={'card'}>
        <div className='card-header bg-info'>
             <strong>USER PROFILE ID NO.</strong>&nbsp; {userIdno}
        </div>
        <div className="card-body">

          <form onSubmit={updateProfile} encType='multipart/form-data' autoComplete='off' method='POST'>
            <div className='row'>
              <div className='col'>
                <div className="mb-3">
                  <label htmlFor="firstname" className="form-label">First Name</label>
                  <input type="text" className="form-control" value={firstname} onChange={e => setFirstname(e.target.value)}/>
                </div>            
                <div className="mb-3">
                  <label htmlFor="lastname" className="form-label">Last Name</label>
                  <input type="text" className="form-control" value={lastname} onChange={e => setLastname(e.target.value)}/>
                </div>            
              </div>
              <div className='col'>
                {
                  profilepic === '' ?
                  <Image id="userpic" className={styles.userprofile} src={usrpic} alt=''/>
                  :
                  <Image id="userpic" className={styles.userprofile} src={profilepic} alt=''/>
                }
                    <div className="mb-3 mt-2">
                      <input type="file" onChange={e => changeProfilepic(e)} className="form-control form-control-sm" id="profilepic"/>
                    </div>                                    
              </div>
            </div>

            <div className='row'>
              <div className='col'>
                <div className="mb-3">
                  <label htmlFor="email" className="form-label">Email Address</label>
                  <input type="email" readOnly className="form-control" value={email} onChange={e => setEmail(e.target.value)}/>
                </div>            
              </div>
              <div className='col'>
                <div className="mb-3">
                  <label htmlFor="mobile" className="form-label">Mobile No.</label>
                  <input type="text" className="form-control" value={mobile} onChange={e => setMobile(e.target.value)}/>
                </div>            
              </div>              
            </div>

            <button type='submit' className='btn btn-info mt-2 mb-2'>save profile</button>
            <hr/>
            {/* TAB CONTENT OPTIONS */}
            <nav>
              <div className="nav nav-tabs" id="nav-tab" role="tablist">
                <button className="nav-link" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Change Password</button>
                <button className="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">2-Factor Authentication</button>
              </div>
            </nav>
            {/* Tab Content # 1 */}
            <div className="tab-content" id="nav-tabContent">
                <div className="tab-pane fade show" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabIndex={0}>
                
                <div className='row mt-3'>
                <div className='col'>
                      <div id="cpwd"> 
                        <div className="mb-3">
                          <input type="text" className="form-control" value={password} onChange={e => setPassword(e.target.value)} placeholder='enter new password.'/>
                        </div>            
                      </div>
                      <button onClick={changePassword} type='button' className='btn btn-primary'>change password</button>

                 </div>
                 <div className='col'>
                      <div className="mb-3">
                          <input type="text" className="form-control" value={confpassword} onChange={e => setConfpassword(e.target.value)} placeholder='enter new password confirmation.'/>
                      </div>                 
                  </div>
              </div>
            </div>
              {/* Tab Content #2 */}
              <div className="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabIndex={0}>
                  
                  <div className='row'>
                      <div className='col'>

                        <p className='text-danger'><strong>REQUIREMENTS</strong></p>
                          <p>You need to install <strong>Google or Microsoft Authenticator</strong> in your Mobile Phone, once installed, click Enable Button below, and <strong>SCAN QR CODE</strong>, next time you login, another dialog window will appear, then enter the <strong>OTP CODE</strong> from your Mobile Phone in order for you to login.</p>
                          <div className='row'>
                            <div className='col-auto'>
                              <button onClick={activateMFA} type="button" className='btn btn-success'>Enable</button>
                            </div>
                            <div className='col-auto'>
                              <button onClick={deactivateMFA} type="button" className='btn btn-secondary'>Disable</button>                        
                            </div>
                          </div>


                      </div>
                      <div className='col'>
                        {
                          qrcode === '' ?
                            <Image className={styles.qrcode1} src={qcode} alt='' />
                        :
                        <div className={styles.qrcode2}>
                          <QRCodeCanvas value={qrcode} />
                        </div>
                        }

                      </div>
                  </div>
              </div>              
            </div>
          </form>    
        </div>
        <div className='card-footer text-danger'>{message}</div>
      </div>
      </main>    
      
    </div>
  )
}

// My-Programs/DotnetCore/core7-mongodb-angular14/clientapp/src/app/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, NgForm, Validators } from '@angular/forms';
import { ProfileService } from '../services/profile.service';

declare var $:any;

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})

export class ProfileComponent implements OnInit {
  
  profileData: any;
  profileMsg: any;
  userId: any;
  jwttoken: any;
  xrey: any = [];
  mfa: boolean = false;
  firstname: string = '';
  lastname: string = '';
  email: string = '';
  mobile: string = '';
  profilepic: string = '';
  password: string  = '';
  confpassword: string = '';
  qrcodeurl: any = null;

  constructor(
    private profileService: ProfileService
  ) 
  {
     this.userId = sessionStorage.getItem("USERID");
     this.jwttoken = sessionStorage.getItem("TOKEN");
     this.profileService.getUserbyId(this.userId, this.jwttoken).subscribe((res: any) => {
         if(res.statuscode == 200) {
            this.firstname = res.user.firstname;
            this.lastname = res.user.lastname;
            this.email = res.user.email;
            this.mobile = res.user.mobile;
            this.profilepic = res.user.profilepic;
            sessionStorage.setItem("USERPIC", res.user.profilepic);
            if (res.user.qrcodeurl != null) {
              const img = new Image();
              img.src = res.user.qrcodeurl;
              this.mfa = true;
              this.qrcodeurl = img.src;
            } else {
              this.mfa = false;
            }
         } else {
           this.profileMsg = res.message;

         }
     });

  }

  ngOnInit(): void {
    $("#cpwd").hide();
    $("#mfa1").hide();
    $("#mfa2").hide();  
  }

  changeProfilepic(event: any) {
    $("#pix").attr('src',URL.createObjectURL(event.target.files[0]));
    
    let formdata = new FormData();
    formdata.append('id', this.userId);
    formdata.append('profilepic',event.target.files[0]);

    this.profileService.UploadPicture(formdata, this.jwttoken).subscribe((res: any) => {
      if(res.statuscode == 200) {
        this.profileMsg = res.message;
        window.setTimeout(() => {
          window.location.reload();
        }, 3000);
      } else {
        this.profileMsg = res.message;
      }
    });    
  }

  changePassword() {
    if ($('#changepwd').is(":checked")) {
      $("#cpwd").show();
      $("#mfa1").hide();  
      $("#mfa2").hide();  
      $('#twofactor').prop('checked', false);
    } else {
      $("#cpwd").hide();
    }            
  }

  onetimePassword() {
    if ($('#twofactor').is(":checked")) {
      $("#cpwd").hide();
      $("#mfa1").show();
      $("#mfa2").show();
      $('#changepwd').prop('checked', false);
    } else {
      $("#mfa1").hide();  
      $("#mfa2").hide();  
    }            
  }

  enableMFA(event: any) {
    event.preventDefault();    
    this.xrey = {
      twofactorenabled: true
    }

    this.profileService.ActivateMFA(this.userId, this.xrey, this.jwttoken).subscribe((res: any) => {
      console.log(res);
      if(res.statuscode == 200) {
        this.profileMsg = res.message;
      } else {
        this.profileMsg = res.message;
      }
      window.setTimeout(() => {
        this.profileMsg = null;
        window.location.reload();
      }, 3000);
  
    });
  }

  disableMFA(event: any) {
    event.preventDefault();    

    this.xrey = {
      twofactorenabled: false
    }

    this.profileService.ActivateMFA(this.userId, this.xrey, this.jwttoken).subscribe((res: any) => {
      if(res.statuscode == 200) {
        this.profileMsg = res.message;
      } else {
        this.profileMsg = res.message;
      }
    });
    window.setTimeout(() => {
      this.profileMsg = null;
      window.location.reload();
    }, 3000);

  }

  submitProfileForm(profileForm:NgForm) {
  
      this.profileData = profileForm.value;
      if (this.profileData.password != null) {
        if (this.profileData.password != this.profileData.confpassword) {
          this.profileMsg = "Password not matched.";
          return;
        }  
      }

      this.profileService.sendProfileRequest(this.userId, this.profileData, this.jwttoken).subscribe((res: any) => {
         if(res.statuscode == 200) {
           this.profileMsg = res.message;
           window.setTimeout(() => {
             this.profileMsg  = null;
             window.location.reload();
           }, 3000);

         } else {
           this.profileMsg = res.message;
           window.setTimeout(() => {
             this.profileMsg  = null;
           }, 3000);
         }
     });      
  }
}

<div class="container">
    <div class="card mt-3 mb-4">
        <div class="card-header">
          USER PROFILE NO.&nbsp; {{userId}}
        </div>
        <div class="card-body">
            <form #profileForm="ngForm" (ngSubmit)="submitProfileForm(profileForm)" novalidate enctype="multipart/form-data" autocomplete="off">
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        

                        <input type="text" [(ngModel)]="firstname" #ctrl="ngModel" class="form-control" name="firstname" id="firstname" required placeholder="enter First Name" >
                      </div>
                      <div class="mb-3">
                        <input type="text" [(ngModel)]="lastname" #ctrl="ngModel" class="form-control" name="lastname" id="lastname"required placeholder="enter Last Name">
                      </div>                      
                      <div class="mb-3">
                        <input type="email"  [(ngModel)]="email" #ctrl="ngModel" class="form-control"  name="email" id="email" readonly>
                      </div>                      
                      <div class="mb-3">
                        <input type="text" [(ngModel)]="mobile" #ctrl="ngModel" class="form-control" name="mobile" id="mobile" required placeholder="enter Mobile No.">
                      </div>                      
                </div>
                <div class="col">
                    <div class="mb-3 text-left">
                        <img id="pix" class="userpic" [src]="profilepic" name="profilepic" [alt]="profilepic" />
                    </div>
                    <div class="mb-3 text-left">
                        <input (change)="changeProfilepic($event)" class="form-control form-control-sm" #userpic="ngModel" name="userpic" id="userpic" type="file" accept=".png, .jpg, .jpeg, .gif" ngModel>
                    </div>                            
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-check">
                        <input (change)="changePassword()" class="form-check-input" type="checkbox" value="" id="changepwd">
                        <label class="form-check-label" for="changepwd">
                          Change Password
                        </label>
                    </div>
                    <div id="cpwd">
                        <div class="mb-3">
                            <input type="text" class="form-control"  [(ngModel)]="password" name="password" placeholder="enter new Password" autocomplete="off">
                          </div>                      
                          <div class="mb-3">
                            <input type="text" class="form-control" [(ngModel)]="confpassword" name="confpassword" placeholder="confirm new Password" autocomplete="off">
                          </div>                              
                    </div>
                    <div id="mfa1">
                        <div *ngIf="mfa == true">
                            <img class="qrcode1" [src]="qrcodeurl" [alt]="qrcodeurl"/>
                        </div>
                        <div *ngIf="mfa == false">
                            <img class="qrcode2" src="http://localhost:5073/resources/images/qrcode.png" alt="QRCODE" />
                        </div>

                    </div>

                </div>
                <div class="col">
                    <div class="form-check">
                        <input (change)="onetimePassword()" class="form-check-input" type="checkbox" value="" id="twofactor">
                        <label class="form-check-label" for="twofactor">
                          2-Factor Authenticator
                        </label>
                    </div>
                    <div id="mfa2">
                        <p class='text-danger'><strong>Requirements</strong></p>
                        <p>You need to install <strong>Google or Microsoft Authenticator</strong> in your Mobile Phone, once installed, click Enable Button below, and <strong>SCAN QR CODE</strong>, next time you login, another dialog window will appear, then enter the <strong>OTP CODE</strong> from your Mobile Phone in order for you to login.</p>
                        <div class="row">
                            <div class="col btn-1">
                                <button (click)="enableMFA($event)" type="button" class="btn btn-primary">Enable</button>
                            </div>
                            <div class="col col-3 btn-2">
                                <button (click)="disableMFA($event)" type="button" class="btn btn-secondary">Disable</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <button id="save" type="submit" class="btn btn-primary">save</button>
        </form>
        </div>
        <div class="card-footer text-danger fsize-12">
            {{profileMsg}}
          </div>



      </div>
</div>
