// My-Programs/DotnetCore/core7-mongodb-angular14/clientapp/src/app/layout/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  userName: any;
  profilepic: any;

  constructor(

  ) { 
    this.userName = sessionStorage.getItem("USERNAME");
    this.profilepic = sessionStorage.getItem('USERPIC');
  }

  ngOnInit(): void {
  }


  isExpanded = false;

  collapse() {
    this.isExpanded = false;
  }
  logOut(){
    sessionStorage.removeItem("USERNAME");
    sessionStorage.clear();
    window.location.reload();
  }
}

<header>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" [routerLink]="['/']"><img class="logo" src="http://localhost:5144/resources/images/logo.png" alt="Qatar Foundation"/></a>          
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link text-dark" [routerLink]="['aboutus']">About Us</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Services
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" [routerLink]="['productlist']">Listings</a></li>
                <li><a class="dropdown-item" [routerLink]="['productcatalog']">Catalogs</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" [routerLink]="['productsearch']">Search Product</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" [routerLink]="['locateus']">Locate Us</a>  
            </li>
          </ul>
          
            <div *ngIf="userName">
              <ul class="navbar-nav mr-auto">
  
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <img class="user" [src]="profilepic" />&nbsp;{{userName}}
                </a>
                <ul class="dropdown-menu">
                  <li><a (click)="logOut()" class="dropdown-item" href="#">Logout</a></li>
                  <li><a class="dropdown-item" [routerLink]="['profile']">Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Messenger</a></li>
                </ul>
              </li>
            </ul>          
  
            </div>
  
            <div *ngIf="!userName">
              <ul class="navbar-nav mr-auto">
  
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#" data-bs-toggle="modal" data-bs-target="#staticLogin">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#" data-bs-toggle="modal" data-bs-target="#staticRegistration">Register</a>
              </li>                    
              </ul>
            </div>
  
          
        </div>
      </div>
    </nav>
  </header>
  <!-- OFF CANVAS -->
  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header bg-primary">
      <h5 class="offcanvas-title text-white" id="offcanvasExampleLabel">Drawer Menu</h5>
      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
  
      <ul class="nav flex-column">
        <li class="nav-item" data-bs-dismiss="offcanvas">
          <a class="nav-link text-dark" [routerLink]="['aboutus']">About Us</a>
        </li>
        <li><hr/></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Services
          </a>
          <ul class="dropdown-menu">
            <li data-bs-dismiss="offcanvas"><a class="dropdown-item" [routerLink]="['productlist']">Listings</a></li>
            <li data-bs-dismiss="offcanvas"><a class="dropdown-item" [routerLink]="['productcatalog']">Catalogs</a></li>
            <li><hr class="dropdown-divider"></li>
            <li data-bs-dismiss="offcanvas"><a class="dropdown-item" [routerLink]="['productsearch']">Search Product</a></li>
          </ul>
        </li>
        <li><hr/></li>
  
        <li class="nav-item" data-bs-dismiss="offcanvas">
          <a class="nav-link text-dark" [routerLink]="['locateus']">Locate Us</a>  
        </li>
        <li><hr/></li>
  
        <div *ngIf="userName">
          <ul class="nav">
  
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img class="user" [src]="profilepic" />&nbsp;{{userName}}
            </a>
            <ul class="dropdown-menu">
              <li data-bs-dismiss="offcanvas"><a (click)="logOut()" class="dropdown-item" href="#">Logout</a></li>
              <li data-bs-dismiss="offcanvas"><a class="dropdown-item" [routerLink]="['profile']">Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li data-bs-dismiss="offcanvas"><a class="dropdown-item" href="#">Messenger</a></li>
            </ul>
          </li>
        </ul>          
        <li><hr/></li>
  
        </div>
  
        <div *ngIf="!userName">
          <ul class="nav flex-column">
  
          <li data-bs-dismiss="offcanvas" class="nav-item">
            <a class="nav-link active" aria-current="page" href="#" data-bs-toggle="modal" data-bs-target="#staticLogin">Login</a>
          </li>
          <li><hr/></li>
  
          <li data-bs-dismiss="offcanvas" class="nav-item">
            <a class="nav-link active" aria-current="page" href="#" data-bs-toggle="modal" data-bs-target="#staticRegistration">Register</a>
          </li>     
          <li><hr/></li>
                 
          </ul>
        </div>
  
      </ul>
  
    </div>
  </div>
  
  <app-login></app-login>
  <app-registration></app-registration>

// My-Programs/NextJS/next14_api_mysql/src/app/header.tsx
'use client';

import Link from 'next/link'
import React from 'react'
import Image from 'next/image'
import logo from './public/next.svg';
import userpic from './public/users/pix.jpg';

import styles from './page.module.css';
import Signin from './[auth]/signin';
import Signup from './[auth]/signup';

export default function Header() {

  const getFromLocalStorage = (key: string) => {
    if (!key || typeof window === 'undefined') {
        return ""
    }
    return localStorage.getItem(key)
  }
  const user = { username: getFromLocalStorage('USERNAME') ? JSON.parse(getFromLocalStorage('USERNAME') || '{}') : []};
  let username: any = user.username.username === undefined ? null : user.username.username

  const signOut = () => {
    localStorage.removeItem('USERID')
    localStorage.removeItem('USERNAME')
    localStorage.removeItem('USERPIC')
    localStorage.removeItem('TOKEN')
    window.location.href = "/"
  }

  return (
    <>
    <header>
<nav className="navbar navbar-expand-lg bg-body-tertiary fixed-top">
  <div className="container-fluid">
    <Link className="navbar-brand" href={'/'} ><Image className={styles.xlogo} src={logo} alt=''/></Link>
     <button className='navbar-toggler' type='button' data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarSupportedContent">
      <ul className="navbar-nav me-auto mb-2 mb-lg-0">
        <li className="nav-item">
          <Link className="nav-link active" aria-current="page" href={'/about'}>About Us</Link>
        </li>
        <li className="nav-item dropdown">
          <a className="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul className="dropdown-menu">
            <li><a className="dropdown-item" href="#">Product 1</a></li>
            <li><a className="dropdown-item" href="#">Product 2</a></li>
            <li><hr className="dropdown-divider"/></li>
            <li><a className="dropdown-item" href="#">Product 3</a></li>
          </ul>
        </li>
        <li className="nav-item">
          <Link className="nav-link" href={'/contact'}>Contact Us</Link>
        </li>
      </ul>

    {
      username === null ?
      <ul className="navbar-nav mr-auto">
        <li className="nav-item">
          <a className="nav-link active" aria-current="page" href="#/" data-bs-toggle="modal" data-bs-target="#staticSigninBackdrop">Signin</a>
        </li>
        <li className="nav-item">
          <a className="nav-link active" aria-current="page" href="#/" data-bs-toggle="modal" data-bs-target="#staticSignupBackdrop">Signup</a>
        </li>
    </ul>
: 
        <div className={styles.unameleft}>
         <li className="nav-item dropdown">
           <a className="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             <span className={styles.user}><Image className={styles.user} src={userpic} alt=''/></span>&nbsp;<span>{username}</span>
           </a>
           <ul className={'dropdown-menu styles.unameleft'}>
             <li><a onClick={signOut} className="dropdown-item" href="#/">Signout</a></li>
             <li><Link className="dropdown-item" href={'/profile'}>Profile</Link></li>
             <li><hr className="dropdown-divider"/></li>
             <li><a className="dropdown-item" href="#/">Messenger</a></li>
           </ul>
         </li>
         </div>  
}





    </div>
  </div>
</nav>
</header>

{/* DRAWER MENU */}
<div className={"offcanvas offcanvas-end styles.drawermenu"} tabIndex={-1} id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div className="offcanvas-header bg-secondary">
    <h5 className="offcanvas-title text-white" id="offcanvasExampleLabel">Drawer Menu</h5>
    <button type="button" className="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div className="offcanvas-body">

  <ul className="nav flex-column">
  <li className="nav-item" data-bs-dismiss="offcanvas">
    <Link className="nav-link active" aria-current="page" href={'/about'}>About Us</Link>
  </li>
  <hr/>
  <li className="nav-item dropdown">
    <a className="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Products
    </a>
    <ul className="dropdown-menu">
      <li data-bs-dismiss="offcanvas"><a className="dropdown-item" href="#">Product 1</a></li>
      <li><hr className="dropdown-divider"/></li>
      <li data-bs-dismiss="offcanvas"><a className="dropdown-item" href="#">Product 2</a></li>
      <li><hr className="dropdown-divider"/></li>
      <li data-bs-dismiss="offcanvas"><a className="dropdown-item" href="#">Product 3</a></li>
    </ul>
  </li>
  <hr/>
  <li className="nav-item" data-bs-dismiss="offcanvas">
    <Link className="nav-link" href={'/contact'}>Contact Us</Link>
  </li>
  <hr/>
  {
      username === null ?

      <ul className="navbar-nav mr-auto">
        <li className="nav-item" data-bs-dismiss="offcanvas">
          <Link className="nav-link active text-primary" href={'#/'} data-bs-toggle="modal" data-bs-target="#staticSigninBackdrop">&nbsp;&nbsp;&nbsp;Signin</Link>
        </li>
      <hr/>    
      <li className="nav-item" data-bs-dismiss="offcanvas">
        <Link className="nav-link active text-primary" href={'#/'} data-bs-toggle="modal" data-bs-target="#staticSignupBackdrop">&nbsp;&nbsp;&nbsp;Signup</Link>
      </li>              
    </ul>    
  : 
        <div>
         <li className="nav-item dropdown">
           <a className="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             <span className={styles.user}><Image className={styles.user} src={userpic} alt=''/></span>&nbsp;<span>{username}</span>
           </a>
           <ul className={'dropdown-menu styles.unameleft'}>
             <li data-bs-dismiss="offcanvas"><a onClick={signOut} className="dropdown-item" href="#/">Signout</a></li>
             <li><hr className="dropdown-divider"/></li>
             <li data-bs-dismiss="offcanvas"><Link className="dropdown-item" href={'/profile'}>Profile</Link></li>
             <li><hr className="dropdown-divider"/></li>
             <li data-bs-dismiss="offcanvas"><a className="dropdown-item" href="#/">Messenger</a></li>
           </ul>
         </li>
         </div>  
    }
  <hr/>
</ul>
  </div>
</div>


<Signin/>
<Signup/>
</>
  )
}
