// My-Programs/DotnetCore/core7-mongodb-angular14/clientapp/src/app/auth/mfa/mfa.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, NgForm, Validators } from '@angular/forms';
import { MfaService } from 'src/app/services/mfa.service';

@Component({
  selector: 'app-mfa',
  templateUrl: './mfa.component.html',
  styleUrls: ['./mfa.component.css']
})
export class MfaComponent implements OnInit {

  mfaData: any;
  mfaMessage: any;
  otp: string = '';
  userId: any;
  mfaPost: any;

  constructor(
    private mfaService: MfaService
  ) { 
    this.userId = sessionStorage.getItem('USERID');
  }

  ngOnInit(): void {
  }

  submitMfaForm(mfaForm:NgForm) {
    if (mfaForm.valid) {
      this.mfaData = mfaForm.value;
      if (this.mfaData.otp === '') {
        this.mfaMessage="Please enter OTP Code."
        window.setTimeout(() => {
          this.mfaMessage=null;
        }, 3000);
        return;
      }

      this.mfaPost = {
        id: this.userId,
        otp: this.mfaData.otp
      }
      this.mfaService.sendMfaValidationRequest(this.mfaPost).subscribe((res: any) => {
        if (res.statuscode == 200) {
          this.mfaMessage = res.message;
          sessionStorage.setItem("USERNAME", res.username);
          window.setTimeout(() => {
            window.location.reload();
          }, 3000);

        } else {
          this.mfaMessage = res.message;
          window.setTimeout(() => {
            this.mfaMessage = null;
          }, 3000);
        }
      }
      )
    }
  }
}

<div class="modal fade" id="staticMfa" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticMfaLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header bg-primary">
          <h1 class="modal-title fs-5 text-white" id="staticMfaLabel">2-Factor Authenticator</h1>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form #mfaForm="ngForm" (ngSubmit)="submitMfaForm(mfaForm)" novalidate autocomplete="off">

          <div class="mb-3">
            
                <input type="text" class="form-control" [(ngModel)]="otp" name="otp" placeholder="enter 6 digits OTP Code">
              </div>
              <button type="submit" class="btn btn-primary">submit</button>
          </form>
        </div>
        <div class="modal-footer">
            <div class="w-100 text-left text-danger fsize-12">{{mfaMessage}}</div>
        </div>
      </div>
    </div>
  </div>

// My-Programs/NextJS/next14_api_mysql/src/app/[auth]/mfa.tsx
import React from 'react'
import { useState } from "react"

export default function Mfa() {
    const [otpcode, setOtpcode] = useState('');
    const [message, setMessage] = useState('');
    const [dizable, setDizable] = useState(false);
    
    const getFromLocalStorage = (key: string) => {
      if (!key || typeof window === 'undefined') {
          return ""
      }
      return localStorage.getItem(key)
    }
  
    const idno = { userid: getFromLocalStorage('USERID') ? JSON.parse(getFromLocalStorage('USERID') || '{}') : []};
    let userIdno: any = idno.userid.userid === undefined ? null : idno.userid.userid
  

    const closeMFA = () => {
        localStorage.clear();
        window.location.href="/";
    }

    const submitMFA = async (e: any) => {
        e.preventDefault();
        setDizable(true);
        setMessage('wait..validating OTP code.');
        let response = await fetch('/api/users/token/validate', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              "id": userIdno,
              "otpcode": otpcode}) 

          }).catch((e: any) => {
            setMessage(e.message);
            setDizable(false);
            return;
          });

          const result = await response?.json()          
          if (result.status === 200) {
              setMessage(result.message);
              const usrname =JSON.stringify({username: result.username});
              localStorage.setItem('USERNAME', usrname);
              setTimeout(() => {
                window.location.href="/";
              }, 3000);
              
          } else {

            setMessage(result.message);
            setTimeout(() => {
              setMessage("");
            }, 3000);
            setDizable(false);
          }

    }


    return (
    <div className="modal fade" id="staticMFA" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="staticMFALabel" aria-hidden="true">
    <div className="modal-dialog modal-sm modal-dialog-centered">
        <div className="modal-content">
        <div className="modal-header bg-warning">
            <h1 className="modal-title fs-5 text-white" id="staticMFALabel">2-Factor Authenticator</h1>
            <button onClick={closeMFA} type="button" className="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div className="modal-body">
            <form onSubmit={submitMFA}>
                <div className="mb-3">
                    <input disabled={dizable} type="text" required className="form-control" value={otpcode} onChange={e => setOtpcode(e.target.value)} autoComplete='off' placeholder="enter OTP Code"/>
                </div>            

                <button disabled={dizable} type="submit" className="btn btn-warning">submit</button>
            </form>
        </div>
        <div className="modal-footer">
            <div id="MfaMsg" className="w-100 text-left text-danger">{message}</div>
        </div>
        </div>
    </div>
    </div>
    )
}
